import { LegalPageShell, LegalSection } from './LegalPageShell';

const EFFECTIVE = '28 SEPTEMBER 2026';

const SECTIONS = [
  { id: 'privacy-scope', num: '00', name: 'WHO WE ARE & SCOPE' },
  { id: 'privacy-data', num: '01', name: 'INFORMATION WE PROCESS' },
  { id: 'privacy-exclusions', num: '02', name: 'INFORMATION WE DELIBERATELY DO NOT STORE' },
  { id: 'privacy-sources', num: '03', name: 'WHERE THE INFORMATION COMES FROM' },
  { id: 'privacy-purposes', num: '04', name: 'WHY WE USE THE INFORMATION' },
  { id: 'privacy-basis', num: '05', name: 'LEGAL BASES WHERE REQUIRED' },
  { id: 'privacy-sharing', num: '06', name: 'SERVICE PROVIDERS & DISCLOSURES' },
  { id: 'privacy-retention', num: '07', name: 'RETENTION & DELETION' },
  { id: 'privacy-transfers', num: '08', name: 'INTERNATIONAL PROCESSING' },
  { id: 'privacy-rights', num: '09', name: 'YOUR RIGHTS & CHOICES' },
  { id: 'privacy-security', num: '10', name: 'SECURITY' },
  { id: 'privacy-children', num: '11', name: 'CHILDREN' },
  { id: 'privacy-changes', num: '12', name: 'CHANGES & CONTACT' },
] as const;

export function PrivacyPolicyPage() {
  return (
    <LegalPageShell
      title="PRIVACY POLICY"
      subtitle="How Dev Ledger collects, uses, stores, shares, and deletes personal data."
      effective={EFFECTIVE}
      sections={SECTIONS.map((section) => ({ ...section }))}
    >
      <LegalSection id="privacy-scope" num="00" title="WHO WE ARE & SCOPE">
        <p>
          Dev Ledger is an independent developer-analytics service available at devledger.site and through the
          Dev Ledger GitHub App. References to “Dev Ledger”, “we”, “us”, or “our” mean the operator of that
          service.
        </p>
        <p>
          This policy applies to Dev Ledger’s website, GitHub App, account and sync services, dashboard,
          feedback tools, and product analytics. It does not govern GitHub, Vercel, Supabase, PostHog, or any
          other third-party service under their own terms and privacy notices.
        </p>
      </LegalSection>

      <LegalSection id="privacy-data" num="01" title="INFORMATION WE PROCESS">
        <p>Dev Ledger processes only the information reasonably needed to operate the service and compute development metrics.</p>
        <ul className="space-y-2 list-none">
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">GitHub account data:</span> GitHub user id, login, display name, avatar URL, and GitHub App installation relationship.</li>
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">Repository metadata:</span> repository identifiers, owner/name, private/public status, default branch, primary language, archived/fork status, language byte counts, and sync state.</li>
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">Commit metrics:</span> commit SHA, author GitHub id/login where available, authored and committed timestamps, additions, deletions, and files changed.</li>
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">Pull-request metadata:</span> pull-request id and number, author identifiers, state, and created/closed/merged timestamps.</li>
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">Account operations:</span> server-side session records, sync state, coverage windows, and security-event records.</li>
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">Feedback:</span> the feedback type, title, optional description, optional verified screenshot, and automatic page/range/build context that you choose to submit.</li>
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">Limited product analytics:</span> selected dashboard range, sync lifecycle category, share-card opens/downloads, feedback type, and delete-data completion.</li>
        </ul>
      </LegalSection>

      <LegalSection id="privacy-exclusions" num="02" title="INFORMATION WE DELIBERATELY DO NOT STORE">
        <p>
          Dev Ledger does not persist repository source code, commit messages, pull-request titles, your GitHub
          email address, GitHub OAuth access tokens, GitHub App installation tokens, or raw webhook payload bodies.
        </p>
        <p>
          The technical implementation and current security boundaries are described in the separate{' '}
          <a href="/security" className="text-neutral-300 underline underline-offset-4 hover:text-[#d6ff3e]">Security &amp; Privacy Trust Record</a>.
        </p>
      </LegalSection>

      <LegalSection id="privacy-sources" num="03" title="WHERE THE INFORMATION COMES FROM">
        <p>
          Most service data comes from GitHub after you sign in and install or authorize the Dev Ledger GitHub App.
          Feedback comes directly from you. Security telemetry is generated by Dev Ledger when the service handles
          requests. Product-usage measurements are generated when you interact with specific allowlisted features.
        </p>
        <p>
          Some commit or pull-request author identifiers can relate to collaborators who have not themselves created
          a Dev Ledger account when those identifiers are part of repository history available to your authorized
          GitHub installation.
        </p>
      </LegalSection>

      <LegalSection id="privacy-purposes" num="04" title="WHY WE USE THE INFORMATION">
        <ul className="space-y-2 list-none">
          <li><span className="text-[#d6ff3e]">▸</span> authenticate users and maintain secure sessions;</li>
          <li><span className="text-[#d6ff3e]">▸</span> discover authorized repositories and synchronize development history;</li>
          <li><span className="text-[#d6ff3e]">▸</span> calculate and display code, commit, activity, language, project, and longitudinal metrics;</li>
          <li><span className="text-[#d6ff3e]">▸</span> maintain incremental sync state and recover interrupted sync work;</li>
          <li><span className="text-[#d6ff3e]">▸</span> detect abuse, investigate security failures, and protect accounts and infrastructure;</li>
          <li><span className="text-[#d6ff3e]">▸</span> receive bug reports, feature requests, and product feedback;</li>
          <li><span className="text-[#d6ff3e]">▸</span> understand limited feature usage and improve Dev Ledger without collecting repository content for analytics.</li>
        </ul>
      </LegalSection>

      <LegalSection id="privacy-basis" num="05" title="LEGAL BASES WHERE REQUIRED">
        <p>
          Where applicable data-protection law requires a legal basis, Dev Ledger processes information as necessary
          to provide the service you request, to pursue legitimate interests in securing and improving the service
          where those interests are not overridden by your rights, and on consent where applicable law requires
          consent for a particular activity.
        </p>
        <p>
          You can withdraw consent where processing is actually based on consent. Withdrawal does not affect earlier
          lawful processing.
        </p>
      </LegalSection>

      <LegalSection id="privacy-sharing" num="06" title="SERVICE PROVIDERS & DISCLOSURES">
        <p>Dev Ledger does not sell personal data and does not use GitHub-derived data for advertising.</p>
        <p>Information may be processed by service providers that are necessary to operate Dev Ledger, including:</p>
        <ul className="space-y-2 list-none">
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">GitHub</span> — authentication, GitHub App installation, repository APIs, and webhooks;</li>
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">Vercel</span> — application hosting, delivery, operational logs, and cookieless Web Analytics;</li>
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">Supabase</span> — application database infrastructure;</li>
          <li><span className="text-[#d6ff3e]">▸</span> <span className="text-neutral-300">PostHog</span> — limited product analytics in the EU region, with autocapture, session replay, heatmaps, surveys, console capture, and performance capture disabled in the current configuration.</li>
        </ul>
        <p>
          We may also disclose information when reasonably necessary to comply with law, enforce legal rights, or
          protect users, the service, or others from fraud, abuse, or security threats.
        </p>
      </LegalSection>

      <LegalSection id="privacy-retention" num="07" title="RETENTION & DELETION">
        <p>
          Core account and development analytics are retained while your Dev Ledger account exists or while you choose
          to retain a repository’s history. Disconnect-and-delete removes repository-specific stored data. “Delete My
          Data” removes the Dev Ledger account record and dependent application data and revokes active sessions.
        </p>
        <p>
          Persisted security events target a 30-day retention window. Webhook replay-deduplication records are pruned
          after they become older than 30 days when later valid webhook traffic triggers cleanup. Backups and
          third-party platform analytics follow their own recovery or retention lifecycle and may not disappear at
          exactly the same moment as primary application data.
        </p>
      </LegalSection>

      <LegalSection id="privacy-transfers" num="08" title="INTERNATIONAL PROCESSING">
        <p>
          Dev Ledger is an internet service and its providers may process information in more than one country.
          Where cross-border transfer rules apply, transfers are handled through the provider arrangements and legal
          safeguards available for the relevant service and jurisdiction.
        </p>
      </LegalSection>

      <LegalSection id="privacy-rights" num="09" title="YOUR RIGHTS & CHOICES">
        <p>
          Depending on where you live, applicable law may give you rights to access, correct, delete, restrict, object
          to, or receive a portable copy of personal data, and to withdraw consent where consent is the applicable
          basis. You may also have the right to complain to a competent data-protection authority.
        </p>
        <p>
          Repository access can be changed or revoked through GitHub. Dev Ledger also provides repository-level
          disconnect/delete controls and an account-level “Delete My Data” control.
        </p>
        <p>
          Signed-in users can submit privacy requests through the in-app feedback drawer. If you cannot access your
          account, use the public operator contact associated with the Dev Ledger project. We may need enough
          information to verify that a request relates to you before acting on it.
        </p>
      </LegalSection>

      <LegalSection id="privacy-security" num="10" title="SECURITY">
        <p>
          Dev Ledger uses technical and organizational controls intended to protect account and development data,
          including read-only GitHub permissions, server-side session validation, same-origin mutation checks,
          row-level database controls, a restrictive Content Security Policy, webhook signature verification, secret
          scanning, dependency auditing, and automated test/build gates.
        </p>
        <p>No internet service can guarantee absolute security.</p>
      </LegalSection>

      <LegalSection id="privacy-children" num="11" title="CHILDREN">
        <p>
          Dev Ledger is intended for developers capable of entering into the agreements required to use the service.
          It is not directed to children who cannot lawfully consent to the processing required for an online service
          in their jurisdiction.
        </p>
      </LegalSection>

      <LegalSection id="privacy-changes" num="12" title="CHANGES & CONTACT">
        <p>
          We may update this policy as the service, providers, or legal requirements change. Material updates will be
          reflected by changing the effective date and, where appropriate, providing additional notice in the service.
        </p>
        <p>
          Privacy questions and requests may be submitted through Dev Ledger’s in-app feedback channel. The current
          technical data-handling record is available at <a href="/security" className="text-neutral-300 underline underline-offset-4 hover:text-[#d6ff3e]">/security</a>.
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}
